# This is a TOML document for Financial Forecast

title = "Setelah Beli Sepeda"

# Your current Balance
initial_value = 10000000

# Month to Forecast
# Jan = 1, Feb = 2, Mar = 3, Apr = 4, May = 5, Jun = 6
# Jul = 7, Aug = 8, Sep = 9, Oct = 10, Nov = 11, Dec = 12
initial_month = 2
last_month = 4

# Income
[[monthly.income]]
name = "string3"
value = 20000
[[monthly.income]]
name = "string3"
value = 30000
[[monthly.income]]
name = "string3"
value = 40000

# Expense
[[monthly.expense]]
name = "string"
value = 10000
[[monthly.expense]]
name = "string2"
value = 5000
[[monthly.expense]]
name = "string3"
value = 1000