# This is a TOML document for Financial Forecast

title = "Title"

# Your current Balance
initial_value = 10000000

# Month to Forecast
# Jan = 1, Feb = 2, Mar = 3, Apr = 4, May = 5, Jun = 6
# Jul = 7, Aug = 8, Sep = 9, Oct = 10, Nov = 11, Dec = 12
initial_month = 2
last_month = 4

# Income
[[monthly.income]]
name = "Gajian"
amount = 5000000
include_first_month = true

# Expense
[[monthly.expense]]
name = "Makan"
amount = 1500000
[[monthly.expense]]
name = "Traveling"
amount = 1000000
[[monthly.expense]]
name = "Hadiah"
amount = 500000